### ISSUE TITLE
Line 158 of Step_1_preproc.py

### ISSUE THREAD

**Issue by RoboEvangelist** [stevenwudi/chalearn2014_wudi_lio#3]
Repeated code (or is it?), and the variable "p_i" does not exists.

**Comment by stevenwudi** [comment]
Hey, you are correct. Those lines are repeated and redundant.  I have deleted the lines. 
However, I have a disclaimer: usually journal papers are always one or even two years lagged behind conference papers in terms of  best performing method. My collaborator Lionel Pigou has already used LSTM to achieve much better result. Hence, I kinda stopped maintaining this repo since then. It would be fine if you use this repo as a  pedagogic purpose. I would suggest you go check his website for the newest/better method. Best

**Comment by RoboEvangelist** [comment]
I could not find his github. Is his program also open source?
